name: Cron Task

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: '5 0 */7 * *'

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update clash
        run: |
          pip install -r requirements.txt
          python build.py
      - name: Build the Docker image
        run: |
          tagname=$(cat tagname)
          docker build . --file Dockerfile -t altonhe/clash-for-linux:latest -t altonhe/clash-for-linux:$tagname
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}   
          
      - name: Push the Docker image
        run: |
          tagname=$(cat tagname)
          docker push altonhe/clash-for-linux:latest
          docker push altonhe/clash-for-linux:$tagname